In [1]:
import pandas as pd
import numpy as np 

import warnings
warnings.filterwarnings('ignore')

In [2]:
import os
os.getcwd()
os.chdir("D:\ABHYAZ INTERNSHIP\MTC")

In [3]:
# df1 = df.iloc[:24316,:]
# df2 = df.iloc[24317:,:]
# print("Shape of new dataframes - {} , {}".format(df1.shape, df2.shape))

In [4]:
df1 = pd.read_csv(r'Industries_complete_cleaned_India.csv')
df1.head()

,Company Name,Name,Email ID,Designation,Mobile No,Address,Pincode,City,Website,Company Type,State,Country,Phone
0,SMALL INDL. ASSOCN OF LUD...,PAWAN GARG,NaN,PRESIDENT,0161 2490939 \n9417027411,ST. NO.9 NEAR GURU AK HIGH ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FOCAL POINT ENTREPRENEURS ASSCON\nK 293,SURINDER PAL SINGH,NaN,PRESIDENT,9855738166,.VIII FOCAL POINT –\nMANGLI LUDHIANA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FOCAL POINT IND. WELFARE ASOCN\nE 647,ISHWAR SINGH,NaN,PRESIDENT,98150 00936,VII FOCAL POINT \nLDH,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FOCAL POINT .VIII INDL. ASSOCN\...,O.P. BASSI,NaN,PRESIDENT,9876910610,.VIII F.P. LUDHIANA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SQUARE NUTS MFRS.ASSCON ST.NO.1,BRIJ BHUSHAN,NaN,PRESIDENT,0161 249119\n98140 98455 \n98140 12193,KOT MANGAL SINGH \nLDH,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 989859 entries, 0 to 989858
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Company Name  849895 non-null  object
 1   Name          986392 non-null  object
 2   Email ID      978334 non-null  object
 3   Designation   461128 non-null  object
 4   Mobile No     578692 non-null  object
 5   Address       426994 non-null  object
 6   Pincode       11832 non-null   float64
 7   City          528170 non-null  object
 8   Website       1835 non-null    object
 9   Company Type  956715 non-null  object
 10  State         965993 non-null  object
 11  Country       989201 non-null  object
 12  Phone         412 non-null     object
dtypes: float64(1), object(12)
memory usage: 98.2+ MB

In [6]:
df1['Company Type'].value_counts()

Company Secretary                            370586
Manufacturing                                206481
Consulting Services                           95177
Services                                      56360
Consultant                                    49919
                                              ...
Consultants  Oil Testing                          1
Marine Consultants                                1
Consultants  Brewers                              1
Consultants  Electronic & Microelectronic         1
Sericulture Consultants                           1
Name: Company Type, Length: 166, dtype: int64

In [7]:
df1['Company Type'].unique()

array([nan, 'Consulting Services', 'Manufacturing',
       'Information Technology', 'Government', 'Services', 'Education',
       'Trade', 'Financial', 'IT Enabled Services (ITES)', 'Media',
       'Utility', 'Telecom', 'Professional', 'Company Secretary',
       'Real Estate Consultants', 'Immigration Consultants',
       'Laboratories Testing Consultant',
       'Consultants  Patents & IP(Intellectual Property)',
       'Computer Consultants', 'Consultants  Engineering',
       'Mining Consultants', 'Insurance Consultants', 'Share Consultants',
       'Consultants  Project Management', 'Marketing Consultants',
       'Consultants  Agricultural',
       'Consultants  Earth Resources & Environment',
       'Consultants  Bridge & Tunnel Construction',
       'Consultants  Management', 'Tax Consultants & VAT Practitioners',
       'Electronics & Micro Electronics Consultants',
       'Laboratories Medical  Consultant', 'Trade Mark Consultants',
       'Vaastu Consultants', 'Acoustical Consultants',
       'Electrical Consultants & Contractors', 'Recycling Consultants',
       'Consultants  Technical', 'Consultants  Sericulture',
       'Oil & Gas Industries  Consultants', 'Consultants  Industrial',
       'Travel Consultants', 'College Consultants',
       'Building Construction Consultants', 'Aviation Consultants',
       'Consultants  Human Resources & Manpower', 'Rubber Consultants',
       'Consultants  Food Production', 'Water Purification Consultants',
       'Earth Moving Consultants',
       'Laboratories Research & Development Consultant',
       'Computer Programming Consultants', 'Automobile Consultants',
       'Consultants  ISO9000/ISO14000/QS9000 & ISO/TS16949',
       'Air Conditioning Consultants', 'Foreign Trade Consultants',
       'Automation Consultants', 'Fitness Trainers & Consultants',
       'Radio Broadcasting Consultants', 'Consultants  Excavating',
       'Audio Visual Consultants', 'Consultants  Imports/Exports',
       'Consultants  Oil & Gas', 'Technical Consultants',
       'Consultants  Public Relations', 'Brand Management Consultants',
       'Consultants  Confectionery & Candy', 'Consultants  Blasting',
       'Marine Consultants', 'Consultants  Acoustical',
       'Publishing Consultants',
       'Consultants  Instrumentation Indicating & Control',
       'Consultants  Computer Programming', 'Grooming Consultants',
       'Educational Consultants', 'Consultants  Technicals',
       'Consultants  Horticulture',
       'Consultants  ISO9000/ISO14000/QS 9000 & ISO/TS16949',
       'Communication Consultants', 'Consultants  Indl',
       'Consultants  Sand & Shot Blasting', 'Consultants  Colour',
       'Consultants  Labor Relations', 'Publicity Consultants',
       'Consultants  Air conditioning & Refrigeration',
       'Consultants  Industrial Safety', 'Consultants  Factory Locating',
       'Consultants  Computers',
       'Consultants  Human Resources & Manpower Indl.',
       'Project Management Consultants', 'Swimming Pool Consultants',
       'Pan Card Consultants/Agents', 'Consultants  Chemical Testing',
       'Speech & Language Consultant Services', 'Consultants  Testing',
       'Display Consultants', 'Consultants  Consumer Protection',
       'Structural Consultants', 'Foundry Consultants',
       'Consultants  Safety', 'Chemical Consultants',
       'Earth Resources & Environment Consultants', 'Brewers Consultants',
       'Consultants  Food Processing', 'Laboratory Chemicals Consultant',
       'Consultants  Chemical', 'Laboratories Analytical  Consultant',
       'Oil Testing Consultants', 'Fengshui Consultants',
       'Consultants  Electrical', 'Testing Consultants',
       'Chemical Testing Consultants', 'Factory Locating Consultants',
       'Combustion & Heating Consultants', 'Color Consultants',
       'Terrace Garden Consultants', 'Consultants  Food Preservation',
       'Consultants  Hygiene(Indl)',
       'Inventory Control & Computing Consultant',
       'Consultants  Aviation', 'Personnel Consultants',
       'Food Processing Consultants', 'Consultants  Company Registration',
       'Consultants  Ceramic', 'Industrial Hygiene Consultants',
       'Filing Consultants', 'Refrigeration Consultants',
       'Multimedia Business & Corp. Presentations  Consultant',
       'Consultants  Instrumentation',
       'Consultants  Intl Quality Standards',
       'DVD/CD Duplication/Media Production Consultant',
       'Noise Control Consultants',
       'Instrumentation  Indicating & Control  Consultants',
       'Consultants  Oil Testing',
       'Antiques  Repairing & Restoring Consultant',
       'Diving & Underwater  Consultant',
       'Consultants  Acoustical Design', 'Executive Search Consultants',
       'Wine Consultants', 'Consultants  Rubber',
       'Consultants  Audio Visual', 'Consultants  Aquaculture',
       'Consultants  Labor Relations Indl.',
       'Food Production Consultants', 'Consultants  Wine',
       'Consultants  Marine', 'Consultants  Radio Broadcasting',
       'Consultants  Oil Well Drilling', 'Consultants  Meteorological',
       'Air Purification Consultants', 'ESI & PF Consultants',
       'Consultants  Mining', 'Consultants  Earth Moving',
       'Consultants  Foundry', 'Traffic & Parking Consultants',
       'Consultants  Electronic & Microelectronic',
       'Sericulture Consultants', 'Consultants  Brewers', 'Consultants',
       'BE Project Education Consultants', 'Property Consultants',
       'Overseas Education Consultants',
       'Vehicle Registration Consultants', 'Education Consultants',
       'Pharmaceutical Consultants', 'Consultant'], dtype=object)

In [8]:
# Extracting the reseller(Consulting services) data from main data

In [9]:
df_filtered = df1.loc[(df1['Company Type'].str.contains('Services'))|(df1['Company Type'].str.contains('Consultants'))|(df1['Company Type'].str.contains('Consulting'))|(df1['Company Type'].str.contains('Consultant'))]

In [10]:
df_filtered

,Company Name,Name,Email ID,Designation,Mobile No,Address,Pincode,City,Website,Company Type,State,Country,Phone
169,Om Sai Telecom,Sunder Singh,NaN,NaN,7838854012,Lohia Nagar 301/5,201001.0,Ghaziabad,NaN,Consulting Services,NaN,India,NaN
170,Creative Marketing,Gobind,NaN,NaN,9833945483,Chembur West Abdul Rehman Street 28,400071.0,Mumbai,NaN,Consulting Services,NaN,India,NaN
171,Magus Limited,Imran,NaN,NaN,9930744868,AAI Colony 36,400099.0,Mumbai,www.magussecure.com,Consulting Services,NaN,India,NaN
172,Sachdeva Communication,NaN,NaN,NaN,9810102655,Sarojini Nagar Ina Market 2,110023.0,Delhi,NaN,Consulting Services,NaN,India,NaN
173,Services 24u,Mr ravinder singh,NaN,NaN,9953649795,South Extension Kanpur ambader nager 16/351,110049.0,Delhi,NaN,Consulting Services,NaN,India,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
989365,NaN,ANIRBAN DASGUPTA,adasgupta_1982@rediffmail.com,NaN,NaN,"MIG 9/2, CITY CENTRE HOUSING COMPLEX, CITY CEN...",NaN,Durgapur,NaN,Consultant,West Bangal,India,NaN
989366,NaN,Anji,blessi_anji@yahoo.co.in,NaN,NaN,"28/2672 A, ANJIS , NELLICODE. P.O., THONDAYAD,...",NaN,Calicut/ Kozhikode,NaN,Consultant,Kerla,India,NaN
989367,HDFCSLIC,ShineG,itsshine@gmail.com,NaN,NaN,Naluthengil Puthiyavila Pattolimarket P.O Alap...,NaN,Kollam,NaN,Consultant,Kerla,India,NaN
989368,NaN,EASWARAVILAS,markfenin@rediffmail.com,NaN,NaN,"ESWARAVILAS : 33/2639, P.C.ROAD CHALIKKAVATTOM...",NaN,Cochin/ Kochi/ Ernakulam,NaN,Consultant,Kerla,India,NaN
989369,NaN,GEORGE,ge@yahoo.com,NaN,NaN,"H:NO:KRRA90A KOLATHERI ROAD, PETTA, POONITHURA...",NaN,Cochin/ Kochi/ Ernakulam,NaN,Consultant,Kerla,India,NaN

In [11]:
df_resellers = pd.DataFrame(df_filtered)
df_resellers.head()

,Company Name,Name,Email ID,Designation,Mobile No,Address,Pincode,City,Website,Company Type,State,Country,Phone
169,Om Sai Telecom,Sunder Singh,NaN,NaN,7838854012,Lohia Nagar 301/5,201001.0,Ghaziabad,NaN,Consulting Services,NaN,India,NaN
170,Creative Marketing,Gobind,NaN,NaN,9833945483,Chembur West Abdul Rehman Street 28,400071.0,Mumbai,NaN,Consulting Services,NaN,India,NaN
171,Magus Limited,Imran,NaN,NaN,9930744868,AAI Colony 36,400099.0,Mumbai,www.magussecure.com,Consulting Services,NaN,India,NaN
172,Sachdeva Communication,NaN,NaN,NaN,9810102655,Sarojini Nagar Ina Market 2,110023.0,Delhi,NaN,Consulting Services,NaN,India,NaN
173,Services 24u,Mr ravinder singh,NaN,NaN,9953649795,South Extension Kanpur ambader nager 16/351,110049.0,Delhi,NaN,Consulting Services,NaN,India,NaN

In [12]:
df_resellers.shape

(217480, 13)

In [13]:
df_resellers.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 217480 entries, 169 to 989369
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Company Name  183448 non-null  object
 1   Name          214068 non-null  object
 2   Email ID      206778 non-null  object
 3   Designation   59863 non-null   object
 4   Mobile No     155573 non-null  object
 5   Address       124749 non-null  object
 6   Pincode       11832 non-null   float64
 7   City          157614 non-null  object
 8   Website       1835 non-null    object
 9   Company Type  217480 non-null  object
 10  State         201094 non-null  object
 11  Country       217480 non-null  object
 12  Phone         0 non-null       object
dtypes: float64(1), object(12)
memory usage: 23.2+ MB

In [14]:
# trim white spaces

df_resellers = df_resellers.apply(lambda x: x.str.strip() if x.dtype == 'object' else x)

In [15]:
df_resellers.duplicated().sum()

0

In [16]:
df_resellers = df_resellers.drop_duplicates()
df_resellers

,Company Name,Name,Email ID,Designation,Mobile No,Address,Pincode,City,Website,Company Type,State,Country,Phone
169,Om Sai Telecom,Sunder Singh,NaN,NaN,7838854012,Lohia Nagar 301/5,201001.0,Ghaziabad,NaN,Consulting Services,NaN,India,NaN
170,Creative Marketing,Gobind,NaN,NaN,9833945483,Chembur West Abdul Rehman Street 28,400071.0,Mumbai,NaN,Consulting Services,NaN,India,NaN
171,Magus Limited,Imran,NaN,NaN,9930744868,AAI Colony 36,400099.0,Mumbai,www.magussecure.com,Consulting Services,NaN,India,NaN
172,Sachdeva Communication,NaN,NaN,NaN,9810102655,Sarojini Nagar Ina Market 2,110023.0,Delhi,NaN,Consulting Services,NaN,India,NaN
173,Services 24u,Mr ravinder singh,NaN,NaN,9953649795,South Extension Kanpur ambader nager 16/351,110049.0,Delhi,NaN,Consulting Services,NaN,India,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
989365,NaN,ANIRBAN DASGUPTA,adasgupta_1982@rediffmail.com,NaN,NaN,"MIG 9/2, CITY CENTRE HOUSING COMPLEX, CITY CEN...",NaN,Durgapur,NaN,Consultant,West Bangal,India,NaN
989366,NaN,Anji,blessi_anji@yahoo.co.in,NaN,NaN,"28/2672 A, ANJIS , NELLICODE. P.O., THONDAYAD,...",NaN,Calicut/ Kozhikode,NaN,Consultant,Kerla,India,NaN
989367,HDFCSLIC,ShineG,itsshine@gmail.com,NaN,NaN,Naluthengil Puthiyavila Pattolimarket P.O Alap...,NaN,Kollam,NaN,Consultant,Kerla,India,NaN
989368,NaN,EASWARAVILAS,markfenin@rediffmail.com,NaN,NaN,"ESWARAVILAS : 33/2639, P.C.ROAD CHALIKKAVATTOM...",NaN,Cochin/ Kochi/ Ernakulam,NaN,Consultant,Kerla,India,NaN
989369,NaN,GEORGE,ge@yahoo.com,NaN,NaN,"H:NO:KRRA90A KOLATHERI ROAD, PETTA, POONITHURA...",NaN,Cochin/ Kochi/ Ernakulam,NaN,Consultant,Kerla,India,NaN

In [17]:
df_resellers.rename({})

,Company Name,Name,Email ID,Designation,Mobile No,Address,Pincode,City,Website,Company Type,State,Country,Phone
169,Om Sai Telecom,Sunder Singh,NaN,NaN,7838854012,Lohia Nagar 301/5,201001.0,Ghaziabad,NaN,Consulting Services,NaN,India,NaN
170,Creative Marketing,Gobind,NaN,NaN,9833945483,Chembur West Abdul Rehman Street 28,400071.0,Mumbai,NaN,Consulting Services,NaN,India,NaN
171,Magus Limited,Imran,NaN,NaN,9930744868,AAI Colony 36,400099.0,Mumbai,www.magussecure.com,Consulting Services,NaN,India,NaN
172,Sachdeva Communication,NaN,NaN,NaN,9810102655,Sarojini Nagar Ina Market 2,110023.0,Delhi,NaN,Consulting Services,NaN,India,NaN
173,Services 24u,Mr ravinder singh,NaN,NaN,9953649795,South Extension Kanpur ambader nager 16/351,110049.0,Delhi,NaN,Consulting Services,NaN,India,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
989365,NaN,ANIRBAN DASGUPTA,adasgupta_1982@rediffmail.com,NaN,NaN,"MIG 9/2, CITY CENTRE HOUSING COMPLEX, CITY CEN...",NaN,Durgapur,NaN,Consultant,West Bangal,India,NaN
989366,NaN,Anji,blessi_anji@yahoo.co.in,NaN,NaN,"28/2672 A, ANJIS , NELLICODE. P.O., THONDAYAD,...",NaN,Calicut/ Kozhikode,NaN,Consultant,Kerla,India,NaN
989367,HDFCSLIC,ShineG,itsshine@gmail.com,NaN,NaN,Naluthengil Puthiyavila Pattolimarket P.O Alap...,NaN,Kollam,NaN,Consultant,Kerla,India,NaN
989368,NaN,EASWARAVILAS,markfenin@rediffmail.com,NaN,NaN,"ESWARAVILAS : 33/2639, P.C.ROAD CHALIKKAVATTOM...",NaN,Cochin/ Kochi/ Ernakulam,NaN,Consultant,Kerla,India,NaN
989369,NaN,GEORGE,ge@yahoo.com,NaN,NaN,"H:NO:KRRA90A KOLATHERI ROAD, PETTA, POONITHURA...",NaN,Cochin/ Kochi/ Ernakulam,NaN,Consultant,Kerla,India,NaN

In [18]:
# create a new column in pandas

df_resellers['Company Type']

169       Consulting Services
170       Consulting Services
171       Consulting Services
172       Consulting Services
173       Consulting Services
                 ...
989365             Consultant
989366             Consultant
989367             Consultant
989368             Consultant
989369             Consultant
Name: Company Type, Length: 217480, dtype: object

In [19]:
df_resellers.shape

(217480, 13)

In [20]:
df_resellers.to_csv('Consulting Services.csv', index=False, header=True)

In [21]:
# deleting the reseller data from the main file after extraction

In [22]:
df1 = df1[~((df1['Company Type'].str.contains('Services'))|(df1['Company Type'].str.contains('Consultants'))|(df1['Company Type'].str.contains('Consulting'))|(df1['Company Type'].str.contains('Consultant')))]

In [23]:
df1.head()

,Company Name,Name,Email ID,Designation,Mobile No,Address,Pincode,City,Website,Company Type,State,Country,Phone
0,SMALL INDL. ASSOCN OF LUD...,PAWAN GARG,NaN,PRESIDENT,0161 2490939 \n9417027411,ST. NO.9 NEAR GURU AK HIGH ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FOCAL POINT ENTREPRENEURS ASSCON\nK 293,SURINDER PAL SINGH,NaN,PRESIDENT,9855738166,.VIII FOCAL POINT –\nMANGLI LUDHIANA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FOCAL POINT IND. WELFARE ASOCN\nE 647,ISHWAR SINGH,NaN,PRESIDENT,98150 00936,VII FOCAL POINT \nLDH,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FOCAL POINT .VIII INDL. ASSOCN\...,O.P. BASSI,NaN,PRESIDENT,9876910610,.VIII F.P. LUDHIANA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SQUARE NUTS MFRS.ASSCON ST.NO.1,BRIJ BHUSHAN,NaN,PRESIDENT,0161 249119\n98140 98455 \n98140 12193,KOT MANGAL SINGH \nLDH,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df1.shape

(772379, 13)

In [25]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 772379 entries, 0 to 989858
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Company Name  666447 non-null  object
 1   Name          772324 non-null  object
 2   Email ID      771556 non-null  object
 3   Designation   401265 non-null  object
 4   Mobile No     423119 non-null  object
 5   Address       302245 non-null  object
 6   Pincode       0 non-null       float64
 7   City          370556 non-null  object
 8   Website       0 non-null       object
 9   Company Type  739235 non-null  object
 10  State         764899 non-null  object
 11  Country       771721 non-null  object
 12  Phone         412 non-null     object
dtypes: float64(1), object(12)
memory usage: 82.5+ MB

In [26]:
df1['Company Type'].value_counts()

Company Secretary         370586
Manufacturing             206481
Trade                      36740
Information Technology     35861
Education                  32782
Financial                  32077
Government                 17677
Media                       2840
Telecom                     2586
Utility                     1204
Professional                 401
Name: Company Type, dtype: int64

In [27]:
df1['Company Type'].unique()

array([nan, 'Manufacturing', 'Information Technology', 'Government',
       'Education', 'Trade', 'Financial', 'Media', 'Utility', 'Telecom',
       'Professional', 'Company Secretary'], dtype=object)

In [28]:
df1['Company Type'] = df1['Company Type'].fillna('others')

In [29]:
df1['Company Type'].unique()

array(['others', 'Manufacturing', 'Information Technology', 'Government',
       'Education', 'Trade', 'Financial', 'Media', 'Utility', 'Telecom',
       'Professional', 'Company Secretary'], dtype=object)

In [30]:
df1.to_csv('Industries_India_cleaned.csv', index=False, header=True)

In [31]:
os.chdir("D:\ABHYAZ INTERNSHIP\MTC\Industries Split Data")

In [32]:
# split an Excel sheet data based on values of a column
    
# Use the groupby function to group the data by the column you want to split by:

grouped_data = df1.groupby('Company Type')

In [33]:
# Loop through the groups and save them as separate Excel files:

for group_name, group_data in grouped_data:
    group_data.to_excel(f'{group_name}.xlsx', index=False)

In [ ]:
x=a['Company Name'].str[0:5]

In [ ]:
k=(df['Company Name']==df['Email ID'])